import { serializeConfig, validateExecutableConfig } from '../serialize.ts'
import { validateConfigTemplateRegistryEntry } from '../templates.ts'
import type { CompileConfigInput, CompiledArtifacts, ExecutableConfig, ParameterValue } from '../types.ts'
import { absoluteHttpUrl, denseOwnDataArray, ownDataRecord, rfc3339DateTime, safeToken } from '../../router/validation.ts'
import type { MethodCapability, Recommendation, RouterOutcome, TaskProfile } from '../../router/types.ts'

const methodFields = ['id', 'aliases', 'version', 'modalities', 'maxScale', 'outputs', 'requiredPriors', 'supportedGoals', 'resourceTier', 'installCommand', 'license', 'sourceUrl', 'docsUrl', 'paperUrl', 'executable']
const profileFields = ['id', 'modality', 'scale', 'goals', 'topology', 'priors', 'perturbation', 'weights', 'maxResourceTier', 'minEffectiveDatasets', 'minCriticalCoverage', 'seed']
const recommendationFields = ['methodId', 'roles', 'paretoLayer', 'outrankingFlow', 'conservativeUtility', 'confidence', 'topThreeRetention', 'effectiveDatasets', 'criticalCoverage', 'positiveEvidence', 'positiveEvidenceDetails', 'evidenceLinks', 'limitations', 'excludedAlternatives']
const groups = ['latent_geometry', 'continuity', 'trajectory', 'stability', 'biology', 'resources']
const shell = /^(?:python|python3|pip|pip3)(?: -m pip)? install ([A-Za-z0-9][A-Za-z0-9._-]*==[A-Za-z0-9][A-Za-z0-9._+!-]*)$/
const pythonIdentifier = /^[A-Za-z_][A-Za-z0-9_]*$/

function exact(value: unknown, label: string, fields: readonly string[], optional: readonly string[] = []): Record<string, unknown> { const record = ownDataRecord(value, label); const allowed = new Set([...fields, ...optional]); if (Object.keys(record).some((key) => !allowed.has(key)) || fields.some((key) => !Object.hasOwn(record, key)) || optional.some((key) => Object.hasOwn(record, key) && record[key] === undefined)) throw new Error(`${label} has unknown, missing, or undefined fields`); return record }
function text(value: unknown, label: string): string { if (typeof value !== 'string' || !value.trim() || [...value].some((character) => character.charCodeAt(0) <= 0x1f || character.charCodeAt(0) === 0x7f)) throw new Error(`${label} must be a nonblank control-free string`); return value }
function number(value: unknown, label: string, min = -Infinity, max = Infinity): number { if (typeof value !== 'number' || !Number.isFinite(value) || value < min || value > max) throw new Error(`${label} is invalid`); return value }
function uint32(value: unknown, label: string): number { const parsed = number(value, label, 0, 0xffffffff); if (!Number.isInteger(parsed)) throw new Error(`${label} must be an integer`); return parsed }
function strings(value: unknown, label: string, minimum = 0, check: (entry: string) => boolean = () => true): string[] { const result = denseOwnDataArray(value, label); if (result.length < minimum || result.some((entry) => typeof entry !== 'string' || !check(entry))) throw new Error(`${label} must be a dense valid string array`); return result as string[] }
function enumValue<T>(value: unknown, allowed: readonly T[], label: string): T { if (!allowed.includes(value as T)) throw new Error(`${label} is invalid`); return value as T }

function parseMethod(value: unknown): MethodCapability { const r = exact(value, 'compiler registry method', methodFields); if (!safeToken(r.id) || !safeToken(r.version) || !absoluteHttpUrl(r.sourceUrl) || !absoluteHttpUrl(r.docsUrl) || !absoluteHttpUrl(r.paperUrl) || typeof r.executable !== 'boolean') throw new Error('compiler registry method is invalid'); return { ...r, id: r.id as string, aliases: strings(r.aliases, 'compiler aliases', 0, safeToken), version: r.version as string, modalities: strings(r.modalities, 'compiler modalities', 1, (v) => ['scrna', 'scatac', 'multiome'].includes(v)) as MethodCapability['modalities'], maxScale: enumValue(r.maxScale, ['lt_10k', '10k_50k', '50k_200k', 'gt_200k'] as const, 'compiler maxScale'), outputs: strings(r.outputs, 'compiler outputs', 1, (v) => ['latent', 'graph', 'pseudotime', 'branch', 'metadata'].includes(v)) as MethodCapability['outputs'], requiredPriors: strings(r.requiredPriors, 'compiler priors', 0, (v) => ['time', 'root_state', 'terminal_states', 'labels', 'perturbation'].includes(v)) as MethodCapability['requiredPriors'], supportedGoals: strings(r.supportedGoals, 'compiler goals', 1, (v) => ['latent_representation', 'trajectory_reconstruction', 'fate_decision', 'lineage_contribution'].includes(v)) as MethodCapability['supportedGoals'], resourceTier: enumValue(r.resourceTier, [1, 2, 3] as const, 'compiler resource tier'), installCommand: text(r.installCommand, 'compiler install'), license: text(r.license, 'compiler license'), sourceUrl: r.sourceUrl as string, docsUrl: r.docsUrl as string, paperUrl: r.paperUrl as string, executable: r.executable as boolean } }
function parseProfile(value: unknown): TaskProfile { const r = exact(value, 'compileConfig profile', profileFields, ['candidateMethodIds']); const p = exact(r.priors, 'compileConfig priors', [], ['time', 'root_state', 'terminal_states', 'labels', 'perturbation']); for (const value of Object.values(p)) if (value !== true && value !== false && value !== 'unknown') throw new Error('compileConfig priors are invalid'); const w = exact(r.weights, 'compileConfig weights', groups); let sum = 0; for (const key of groups) sum += number(w[key], `compileConfig weights.${key}`, 0); if (sum <= 0) throw new Error('compileConfig weights must have a positive sum'); const effective = number(r.minEffectiveDatasets, 'compileConfig minEffectiveDatasets', 1); if (!Number.isInteger(effective)) throw new Error('compileConfig minEffectiveDatasets must be an integer'); return { ...r, id: safeToken(r.id) ? r.id : (() => { throw new Error('compileConfig profile id is invalid') })(), modality: enumValue(r.modality, ['scrna', 'scatac', 'multiome'] as const, 'compileConfig modality'), scale: enumValue(r.scale, ['lt_10k', '10k_50k', '50k_200k', 'gt_200k', 'unknown'] as const, 'compileConfig scale'), goals: strings(r.goals, 'compileConfig goals', 1, (v) => ['latent_representation', 'trajectory_reconstruction', 'fate_decision', 'lineage_contribution'].includes(v)) as TaskProfile['goals'], topology: enumValue(r.topology, ['linear', 'bifurcating', 'multibranch', 'cyclic', 'mixed', 'unknown'] as const, 'compileConfig topology'), priors: p as TaskProfile['priors'], perturbation: enumValue(r.perturbation, [true, false, 'unknown'] as const, 'compileConfig perturbation'), weights: w as TaskProfile['weights'], maxResourceTier: enumValue(r.maxResourceTier, [1, 2, 3] as const, 'compileConfig maxResourceTier'), minEffectiveDatasets: effective, minCriticalCoverage: number(r.minCriticalCoverage, 'compileConfig minCriticalCoverage', 0, 1), seed: uint32(r.seed, 'compileConfig profile seed'), ...(r.candidateMethodIds === undefined ? {} : { candidateMethodIds: strings(r.candidateMethodIds, 'compileConfig candidateMethodIds', 0, safeToken) }) } as TaskProfile }
function parseRecommendation(value: unknown): Recommendation { const r = exact(value, 'compileConfig recommendation', recommendationFields); if (!safeToken(r.methodId) || !['high', 'medium', 'low'].includes(r.confidence as string) || !Number.isInteger(number(r.paretoLayer, 'pareto', 0)) || !Number.isInteger(number(r.effectiveDatasets, 'datasets', 0))) throw new Error('compileConfig recommendation is invalid'); for (const key of ['outrankingFlow', 'conservativeUtility'] as const) number(r[key], key); for (const key of ['topThreeRetention', 'criticalCoverage'] as const) number(r[key], key, 0, 1); strings(r.roles, 'roles', 1, (v) => ['best_fit', 'robust_alternative', 'resource_aware'].includes(v)); strings(r.positiveEvidence, 'positiveEvidence'); strings(r.limitations, 'limitations'); for (const item of denseOwnDataArray(r.positiveEvidenceDetails, 'positiveEvidenceDetails')) { const d = exact(item, 'positiveEvidenceDetail', ['text', 'metricIds', 'datasetIds', 'synthetic']); text(d.text, 'positiveEvidenceDetail text'); strings(d.metricIds, 'metricIds', 0, safeToken); strings(d.datasetIds, 'datasetIds', 0, safeToken); if (typeof d.synthetic !== 'boolean') throw new Error('synthetic is invalid') } for (const item of denseOwnDataArray(r.evidenceLinks, 'evidenceLinks')) { const d = exact(item, 'evidenceLink', ['paperId', 'locator', 'datasetId', 'metricId', 'datasetVersion', 'methodVersion', 'runConfigId', 'extractedAt', 'synthetic']); for (const key of ['paperId', 'datasetId', 'metricId', 'datasetVersion', 'methodVersion', 'runConfigId']) if (!safeToken(d[key])) throw new Error(`evidenceLink ${key} is invalid`); if (!rfc3339DateTime(d.extractedAt) || typeof d.synthetic !== 'boolean') throw new Error('evidenceLink is invalid') } for (const item of denseOwnDataArray(r.excludedAlternatives, 'excludedAlternatives')) { const d = exact(item, 'excludedAlternative', ['methodId', 'reasons']); if (!safeToken(d.methodId)) throw new Error('excluded method is invalid'); strings(d.reasons, 'reasons', 1, (v) => ['UNSUPPORTED_MODALITY', 'SCALE_LIMIT', 'RESOURCE_LIMIT', 'MISSING_REQUIRED_PRIOR', 'MISSING_OUTPUT', 'UNSUPPORTED_GOAL', 'NOT_EXECUTABLE', 'NOT_SELECTED_CANDIDATE'].includes(v)) } return r as unknown as Recommendation }
function parseOutcome(value: unknown): Extract<RouterOutcome, { status: 'OK' }> { const r = ownDataRecord(value, 'compileConfig outcome'); if (r.status !== 'OK') throw new Error('compileConfig requires a successful recommendation'); const parsed = exact(r, 'compileConfig outcome', ['status', 'recommendations', 'seed', 'evidenceVersion', 'routerVersion']); if (!safeToken(parsed.evidenceVersion) || !safeToken(parsed.routerVersion)) throw new Error('compileConfig versions must be safe tokens'); const recommendations = denseOwnDataArray(parsed.recommendations, 'recommendations').map(parseRecommendation); if (!recommendations.length) throw new Error('recommendations must be non-empty'); return { status: 'OK', recommendations, seed: uint32(parsed.seed, 'outcome seed'), evidenceVersion: parsed.evidenceVersion as string, routerVersion: parsed.routerVersion as string } }
function freeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const key of Reflect.ownKeys(value)) freeze((value as Record<PropertyKey, unknown>)[key]); Object.freeze(value) } return value }
function python(value: ParameterValue | undefined): string { if (value === undefined) return 'None'; if (typeof value === 'boolean') return value ? 'True' : 'False'; if (typeof value === 'number') return String(value); return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'` }

export function createCompilerEngine(rawMethods: readonly unknown[], rawTemplates: readonly unknown[]): (input: CompileConfigInput) => CompiledArtifacts {
  const methods = denseOwnDataArray(rawMethods, 'compiler methods').map(parseMethod); const templates = denseOwnDataArray(rawTemplates, 'compiler templates').map(validateConfigTemplateRegistryEntry); const methodsById = new Map(methods.map((method) => [method.id, method])); const templatesById = new Map(templates.map((template) => [template.methodId, template])); const identities = new Set<string>(); for (const method of methods) for (const identity of [method.id, ...method.aliases]) { const normalized = identity.toLowerCase(); if (identities.has(normalized)) throw new Error('duplicate canonical method identity'); identities.add(normalized) } if (!methods.length || methodsById.size !== methods.length || templatesById.size !== templates.length || methods.length !== templates.length || methods.some((method) => !templatesById.has(method.id))) throw new Error('compiler registries must be complete')
  return (input) => { const raw = exact(input, 'compileConfig input', ['outcome', 'profile', 'generatedAt'], ['parameters']); const outcome = parseOutcome(raw.outcome); const profile = parseProfile(raw.profile); if (!rfc3339DateTime(raw.generatedAt)) throw new Error('generatedAt must be an RFC3339 date-time'); const best = outcome.recommendations.filter((recommendation) => recommendation.roles.includes('best_fit')); if (best.length !== 1) throw new Error('exactly one best_fit recommendation is required'); const method = methodsById.get(best[0].methodId); const template = templatesById.get(best[0].methodId); if (!method || !template || !method.executable) throw new Error('selected method is not executable'); if (template.version !== method.version || !method.outputs.includes('latent') || !template.outputKeys.latent) throw new Error('method/template mismatch'); const install = shell.exec(method.installCommand); if (!install || !install[1].startsWith(`${template.packageName}==`)) throw new Error('unsafe install command'); const supplied = raw.parameters === undefined ? Object.create(null) : ownDataRecord(raw.parameters, 'parameters'); const parameters: Record<string, ParameterValue> = Object.assign(Object.create(null), template.defaultParameters); for (const [key, value] of Object.entries(supplied)) { const definition = template.allowedParameters[key]; if (!pythonIdentifier.test(key) || value === undefined || !definition || typeof value !== definition.type || (typeof value === 'number' && !Number.isFinite(value))) throw new Error(`invalid parameter ${key}`); if (typeof value === 'number' && ((definition.minimum !== undefined && value < definition.minimum) || (definition.maximum !== undefined && value > definition.maximum) || (definition.integer && !Number.isInteger(value)))) throw new Error(`invalid parameter ${key}`); if (definition.enum && !definition.enum.includes(value as ParameterValue)) throw new Error(`invalid parameter ${key}`); parameters[key] = value as ParameterValue }
    const downstream: ExecutableConfig['downstream'] = Object.create(null); if (template.downstream?.scFocus) { const branchKey = template.downstream.scFocus.branchKey ?? template.outputKeys.branch; if (template.downstream.scFocus.branchKey !== undefined && !template.outputKeys.branch) throw new Error('scFocus requires branch'); downstream.scFocus = { latentKey: template.outputKeys.latent, ...(branchKey === undefined ? {} : { branchKey }), contributionOutput: template.downstream.scFocus.contributionOutput } } if (template.downstream?.scRL) { const pseudotimeKey = template.downstream.scRL.pseudotimeKey ?? template.outputKeys.pseudotime; if (!pseudotimeKey || !template.outputKeys.pseudotime) throw new Error('scRL requires pseudotime'); downstream.scRL = { latentKey: template.outputKeys.latent, pseudotimeKey, decisionOutput: template.downstream.scRL.decisionOutput } }
    const config: ExecutableConfig = { schemaVersion: '1.0', routerVersion: outcome.routerVersion, evidenceVersion: outcome.evidenceVersion, method: { id: method.id, version: method.version, install: method.installCommand }, preprocessing: { modality: profile.modality, normalization: 'library_size_log1p', featureSelection: 'highly_variable_features' }, parameters, outputs: template.outputKeys, downstream, provenance: { recommendationSeed: outcome.seed, methodSource: method.sourceUrl, generatedAt: raw.generatedAt as string, profileFingerprint: '0'.repeat(64), outcome: { status: 'OK', methodId: method.id } } }; const serialized = serializeConfig(config); const stem = `${method.id}-${outcome.routerVersion}-seed-${outcome.seed}`; const lines = [`from ${template.importName} import ${template.constructor}`, '', `model = ${template.constructor}(`]; for (const key of Object.keys(parameters).sort()) lines.push(`    ${key}=${python(parameters[key])},`); lines.push(')', 'result = model.fit_transform(adata)', `adata.obsm[${python(config.outputs.latent)}] = result.latent`); if (config.outputs.graph) lines.push(`adata.obsp[${python(config.outputs.graph)}] = result.graph`); if (config.downstream.scFocus) lines.push(`run_scfocus(adata, latent_key=${python(config.downstream.scFocus.latentKey)}, branch_key=${python(config.downstream.scFocus.branchKey)}, contribution_output=${python(config.downstream.scFocus.contributionOutput)})`); if (config.downstream.scRL) lines.push(`run_scrl(adata, latent_key=${python(config.downstream.scRL.latentKey)}, pseudotime_key=${python(config.downstream.scRL.pseudotimeKey)}, decision_output=${python(config.downstream.scRL.decisionOutput)})`); return freeze({ config: validateExecutableConfig(config), ...serialized, installCommand: method.installCommand, pythonSnippet: `${lines.join('\n')}\n`, filenames: { json: `${stem}.json`, yaml: `${stem}.yaml`, python: `${stem}.py` } }) }
}
