import { serializeConfig, validateExecutableConfig } from '../serialize.ts'
import { validateConfigTemplateRegistryEntry } from '../templates.ts'
import { assertExecutableConfigSchema } from '../schema.ts'
import type { CompileConfigInput, CompiledArtifacts, ExecutableConfig, ParameterValue } from '../types.ts'
import { absoluteHttpUrl, denseOwnDataArray, ownDataRecord, rfc3339DateTime, safeToken } from '../../router/validation.ts'
import type { MethodCapability, Recommendation, RouterOutcome, TaskProfile } from '../../router/types.ts'
import { isSafeCanonicalId } from '../../router/ids.ts'
import { profileFingerprint } from '../../router/release-digest.ts'
import { filterCompatibleMethods } from '../../router/constraints.ts'

export { sha256Hex } from '../../router/release-digest.ts'

const methodFields = ['id', 'aliases', 'version', 'modalities', 'maxScale', 'outputs', 'requiredPriors', 'supportedGoals', 'resourceTier', 'installCommand', 'license', 'sourceUrl', 'docsUrl', 'paperUrl', 'executable']
const profileFields = ['id', 'modality', 'scale', 'goals', 'topology', 'priors', 'perturbation', 'weights', 'maxResourceTier', 'minEffectiveDatasets', 'minCriticalCoverage', 'seed']
const recommendationFields = ['methodId', 'roles', 'paretoLayer', 'outrankingFlow', 'conservativeUtility', 'confidence', 'topThreeRetention', 'effectiveDatasets', 'criticalCoverage', 'positiveEvidence', 'positiveEvidenceDetails', 'evidenceLinks', 'confidenceReasons', 'limitations', 'alternativeDispositions', 'excludedAlternatives']
const groups = ['latent_geometry', 'continuity', 'trajectory', 'stability', 'biology', 'resources']
const shell = /^(?:python(?:3)? -m pip|pip(?:3)?) install ([A-Za-z0-9][A-Za-z0-9._-]*==[A-Za-z0-9][A-Za-z0-9._+!-]*)$/
const pythonIdentifier = /^[A-Za-z_][A-Za-z0-9_]*$/
const outputNames = ['latent', 'graph', 'pseudotime', 'branch', 'metadata'] as const

function exact(value: unknown, label: string, fields: readonly string[], optional: readonly string[] = []): Record<string, unknown> { const record = ownDataRecord(value, label); const allowed = new Set([...fields, ...optional]); if (Object.keys(record).some((key) => !allowed.has(key)) || fields.some((key) => !Object.hasOwn(record, key)) || optional.some((key) => Object.hasOwn(record, key) && record[key] === undefined)) throw new Error(`${label} has unknown, missing, or undefined fields`); return record }
function text(value: unknown, label: string): string { if (typeof value !== 'string' || !value.trim() || [...value].some((character) => character.charCodeAt(0) <= 0x1f || character.charCodeAt(0) === 0x7f)) throw new Error(`${label} must be a nonblank control-free string`); return value }
function number(value: unknown, label: string, min = -Infinity, max = Infinity): number { if (typeof value !== 'number' || !Number.isFinite(value) || value < min || value > max) throw new Error(`${label} is invalid`); return value }
function uint32(value: unknown, label: string): number { const parsed = number(value, label, 0, 0xffffffff); if (!Number.isInteger(parsed)) throw new Error(`${label} must be an integer`); return parsed }
function strings(value: unknown, label: string, minimum = 0, check: (entry: string) => boolean = () => true): string[] { const result = denseOwnDataArray(value, label); if (result.length < minimum || result.some((entry) => typeof entry !== 'string' || !text(entry, label) || !check(entry))) throw new Error(`${label} must be a dense valid string array`); return [...result] as string[] }
function distinct(values: readonly string[], label: string, normalize: (value: string) => string = (value) => value): string[] { if (new Set(values.map(normalize)).size !== values.length) throw new Error(`${label} must not contain duplicates`); return [...values] }
function enumValue<T>(value: unknown, allowed: readonly T[], label: string): T { if (!allowed.includes(value as T)) throw new Error(`${label} is invalid`); return value as T }
function orderedOutputs(values: string[], label: string): string[] { const expected = outputNames.filter((output) => values.includes(output)); if (values.length !== expected.length || values.some((value, index) => value !== expected[index])) throw new Error(`${label} must use canonical output order`); return values }
function equalArrays(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]) }

function parseMethod(value: unknown): MethodCapability { const r = exact(value, 'compiler registry method', methodFields); if (!safeToken(r.id) || !isSafeCanonicalId(r.id as string)) throw new Error('compiler registry method has an unsafe canonical identity'); if (!safeToken(r.version) || !absoluteHttpUrl(r.sourceUrl) || !absoluteHttpUrl(r.docsUrl) || !absoluteHttpUrl(r.paperUrl) || typeof r.executable !== 'boolean') throw new Error('compiler registry method is invalid'); const aliases = distinct(strings(r.aliases, 'compiler aliases', 0, safeToken), 'compiler aliases', (entry) => entry.toLowerCase()); const outputs = orderedOutputs(distinct(strings(r.outputs, 'compiler outputs', 1, (v) => outputNames.includes(v as typeof outputNames[number])), 'compiler outputs'), 'compiler outputs'); const modalities = distinct(strings(r.modalities, 'compiler modalities', 1, (v) => ['scrna', 'scatac', 'multiome'].includes(v)), 'compiler modalities'); const requiredPriors = distinct(strings(r.requiredPriors, 'compiler priors', 0, (v) => ['time', 'root_state', 'terminal_states', 'labels', 'perturbation'].includes(v)), 'compiler priors'); const supportedGoals = distinct(strings(r.supportedGoals, 'compiler goals', 1, (v) => ['latent_representation', 'trajectory_reconstruction', 'fate_decision', 'lineage_contribution'].includes(v)), 'compiler goals'); return { id: r.id as string, aliases, version: r.version as string, modalities: modalities as MethodCapability['modalities'], maxScale: enumValue(r.maxScale, ['lt_10k', '10k_50k', '50k_200k', 'gt_200k'] as const, 'compiler maxScale'), outputs: outputs as MethodCapability['outputs'], requiredPriors: requiredPriors as MethodCapability['requiredPriors'], supportedGoals: supportedGoals as MethodCapability['supportedGoals'], resourceTier: enumValue(r.resourceTier, [1, 2, 3] as const, 'compiler resource tier'), installCommand: text(r.installCommand, 'compiler install'), license: text(r.license, 'compiler license'), sourceUrl: r.sourceUrl as string, docsUrl: r.docsUrl as string, paperUrl: r.paperUrl as string, executable: r.executable as boolean } }
function parseProfile(value: unknown): TaskProfile { const r = exact(value, 'compileConfig profile', profileFields, ['candidateMethodIds']); const p = exact(r.priors, 'compileConfig priors', [], ['time', 'root_state', 'terminal_states', 'labels', 'perturbation']); const priors: TaskProfile['priors'] = Object.create(null); for (const [key, prior] of Object.entries(p)) { if (prior !== true && prior !== false && prior !== 'unknown') throw new Error('compileConfig priors are invalid'); priors[key as keyof TaskProfile['priors']] = prior } const w = exact(r.weights, 'compileConfig weights', groups); const weights = Object.create(null) as TaskProfile['weights']; let sum = 0; for (const key of groups) { weights[key as keyof TaskProfile['weights']] = number(w[key], `compileConfig weights.${key}`, 0); sum += weights[key as keyof TaskProfile['weights']] } if (sum <= 0) throw new Error('compileConfig weights must have a positive sum'); const effective = number(r.minEffectiveDatasets, 'compileConfig minEffectiveDatasets', 1); if (!Number.isInteger(effective)) throw new Error('compileConfig minEffectiveDatasets must be an integer'); if (!safeToken(r.id)) throw new Error('compileConfig profile id is invalid'); const candidateMethodIds = r.candidateMethodIds === undefined ? undefined : distinct(strings(r.candidateMethodIds, 'compileConfig candidateMethodIds', 0, safeToken), 'compileConfig candidateMethodIds'); return { id: r.id, modality: enumValue(r.modality, ['scrna', 'scatac', 'multiome'] as const, 'compileConfig modality'), scale: enumValue(r.scale, ['lt_10k', '10k_50k', '50k_200k', 'gt_200k', 'unknown'] as const, 'compileConfig scale'), goals: distinct(strings(r.goals, 'compileConfig goals', 1, (v) => ['latent_representation', 'trajectory_reconstruction', 'fate_decision', 'lineage_contribution'].includes(v)), 'compileConfig goals') as TaskProfile['goals'], topology: enumValue(r.topology, ['linear', 'bifurcating', 'multibranch', 'cyclic', 'mixed', 'unknown'] as const, 'compileConfig topology'), priors, perturbation: enumValue(r.perturbation, [true, false, 'unknown'] as const, 'compileConfig perturbation'), weights, maxResourceTier: enumValue(r.maxResourceTier, [1, 2, 3] as const, 'compileConfig maxResourceTier'), minEffectiveDatasets: effective, minCriticalCoverage: number(r.minCriticalCoverage, 'compileConfig minCriticalCoverage', 0, 1), seed: uint32(r.seed, 'compileConfig profile seed'), ...(candidateMethodIds === undefined ? {} : { candidateMethodIds }) } }
type ExclusionReason = Recommendation['excludedAlternatives'][number]['reasons'][number]

function parseExclusionReasons(value: unknown): ExclusionReason[] {
  const allowed: readonly ExclusionReason[] = ['UNSUPPORTED_MODALITY', 'SCALE_LIMIT', 'RESOURCE_LIMIT', 'MISSING_REQUIRED_PRIOR', 'MISSING_OUTPUT', 'UNSUPPORTED_GOAL', 'NOT_EXECUTABLE', 'NOT_SELECTED_CANDIDATE']
  const reasons = distinct(strings(value, 'reasons', 1), 'reasons')
  if (reasons.some((reason) => !allowed.includes(reason as ExclusionReason))) throw new Error('reasons are invalid')
  return reasons as ExclusionReason[]
}

function parseRecommendation(value: unknown): Recommendation {
  const r = exact(value, 'compileConfig recommendation', recommendationFields)
  if (!safeToken(r.methodId) || !['high', 'medium', 'low'].includes(r.confidence as string) || !Number.isInteger(number(r.paretoLayer, 'pareto', 0))) throw new Error('compileConfig recommendation is invalid')
  const roles = distinct(strings(r.roles, 'roles', 1, (v) => ['best_fit', 'robust_alternative', 'resource_aware'].includes(v)), 'roles') as Recommendation['roles']
  const positiveEvidence = strings(r.positiveEvidence, 'positiveEvidence')
  const confidenceReasons = strings(r.confidenceReasons, 'confidenceReasons', 1)
  const limitations = strings(r.limitations, 'limitations')
  const positiveEvidenceDetails = denseOwnDataArray(r.positiveEvidenceDetails, 'positiveEvidenceDetails').map((item) => { const d = exact(item, 'positiveEvidenceDetail', ['text', 'group', 'score', 'baseline', 'contribution', 'direction', 'metricIds', 'datasetIds', 'synthetic']); if (typeof d.synthetic !== 'boolean' || d.direction !== 'supports') throw new Error('evidence direction or synthetic status is invalid'); const score = number(d.score, 'evidence score', 0, 1); const baseline = number(d.baseline, 'evidence baseline', 0, 1); const contribution = number(d.contribution, 'evidence contribution', 0); if (score <= baseline || contribution <= 0) throw new Error('positive evidence must exceed its baseline'); return { text: text(d.text, 'positiveEvidenceDetail text'), group: enumValue(d.group, groups, 'evidence group') as Recommendation['positiveEvidenceDetails'][number]['group'], score, baseline, contribution, direction: 'supports' as const, metricIds: distinct(strings(d.metricIds, 'metricIds', 0, safeToken), 'metricIds'), datasetIds: distinct(strings(d.datasetIds, 'datasetIds', 0, safeToken), 'datasetIds'), synthetic: d.synthetic } })
  const evidenceLinks = denseOwnDataArray(r.evidenceLinks, 'evidenceLinks').map((item) => { const d = exact(item, 'evidenceLink', ['paperId', 'locator', 'datasetId', 'metricId', 'datasetVersion', 'methodVersion', 'runConfigId', 'extractedAt', 'synthetic']); for (const key of ['paperId', 'datasetId', 'metricId', 'datasetVersion', 'methodVersion', 'runConfigId']) if (!safeToken(d[key])) throw new Error(`evidenceLink ${key} is invalid`); if (!rfc3339DateTime(d.extractedAt) || typeof d.synthetic !== 'boolean') throw new Error('evidenceLink is invalid'); return { paperId: d.paperId as string, locator: text(d.locator, 'evidenceLink locator'), datasetId: d.datasetId as string, metricId: d.metricId as string, datasetVersion: d.datasetVersion as string, methodVersion: d.methodVersion as string, runConfigId: d.runConfigId as string, extractedAt: d.extractedAt as string, synthetic: d.synthetic } })
  const excludedAlternatives = denseOwnDataArray(r.excludedAlternatives, 'excludedAlternatives').map((item) => { const d = exact(item, 'excludedAlternative', ['methodId', 'reasons']); if (!safeToken(d.methodId)) throw new Error('excluded method is invalid'); return { methodId: d.methodId as string, reasons: parseExclusionReasons(d.reasons) } })
  const alternativeDispositions = denseOwnDataArray(r.alternativeDispositions, 'alternativeDispositions').map((item) => { const d = exact(item, 'alternativeDisposition', ['methodId', 'status', 'reasons']); if (!safeToken(d.methodId)) throw new Error('alternative method is invalid'); return { methodId: d.methodId as string, status: enumValue(d.status, ['recommended_alternative', 'compatible_unselected', 'excluded'] as const, 'alternative disposition'), reasons: distinct(strings(d.reasons, 'alternative reasons', 1), 'alternative reasons') } })
  if (new Set(excludedAlternatives.map((entry) => entry.methodId)).size !== excludedAlternatives.length) throw new Error('excludedAlternatives must not contain duplicate method IDs')
  if (new Set(alternativeDispositions.map((entry) => entry.methodId)).size !== alternativeDispositions.length) throw new Error('alternativeDispositions must not contain duplicate method IDs')
  return { methodId: r.methodId as string, roles, paretoLayer: number(r.paretoLayer, 'pareto', 0), outrankingFlow: number(r.outrankingFlow, 'outrankingFlow'), conservativeUtility: number(r.conservativeUtility, 'conservativeUtility'), confidence: r.confidence as Recommendation['confidence'], topThreeRetention: number(r.topThreeRetention, 'topThreeRetention', 0, 1), effectiveDatasets: number(r.effectiveDatasets, 'datasets', 0), criticalCoverage: number(r.criticalCoverage, 'criticalCoverage', 0, 1), positiveEvidence, positiveEvidenceDetails, evidenceLinks, confidenceReasons, limitations, alternativeDispositions, excludedAlternatives }
}
function parseOutcome(value: unknown): Extract<RouterOutcome, { status: 'OK' }> { const r = ownDataRecord(value, 'compileConfig outcome'); if (r.status !== 'OK') throw new Error('compileConfig requires a successful recommendation'); const parsed = exact(r, 'compileConfig outcome', ['status', 'recommendations', 'seed', 'evidenceVersion', 'routerVersion', 'receipt']); if (!safeToken(parsed.evidenceVersion) || !safeToken(parsed.routerVersion)) throw new Error('compileConfig versions must be safe tokens'); const receipt = exact(parsed.receipt, 'compileConfig receipt', ['profileFingerprint', 'release']); const release = exact(receipt.release, 'compileConfig release receipt', ['id', 'synthetic', 'description', 'configDigest', 'evidenceDigest']); if (!/^[a-f0-9]{64}$/.test(String(receipt.profileFingerprint)) || !safeToken(release.id) || typeof release.synthetic !== 'boolean' || !text(release.description, 'release description') || !/^[a-f0-9]{64}$/.test(String(release.configDigest)) || !/^[a-f0-9]{64}$/.test(String(release.evidenceDigest)) || release.id !== parsed.evidenceVersion) throw new Error('compileConfig receipt is invalid'); const recommendations = denseOwnDataArray(parsed.recommendations, 'recommendations').map(parseRecommendation); if (!recommendations.length) throw new Error('recommendations must be non-empty'); return { status: 'OK', recommendations, seed: uint32(parsed.seed, 'outcome seed'), evidenceVersion: parsed.evidenceVersion as string, routerVersion: parsed.routerVersion as string, receipt: { profileFingerprint: receipt.profileFingerprint as string, release: { id: release.id as string, synthetic: release.synthetic as boolean, description: release.description as string, configDigest: release.configDigest as string, evidenceDigest: release.evidenceDigest as string } } } }
function freeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const key of Reflect.ownKeys(value)) freeze((value as Record<PropertyKey, unknown>)[key]); Object.freeze(value) } return value }
function python(value: ParameterValue | undefined): string { if (value === undefined) return 'None'; if (typeof value === 'boolean') return value ? 'True' : 'False'; if (typeof value === 'number') return String(value); return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'` }

export function createCompilerEngine(rawMethods: readonly unknown[], rawTemplates: readonly unknown[]): (input: CompileConfigInput) => CompiledArtifacts {
  const methods = denseOwnDataArray(rawMethods, 'compiler methods').map(parseMethod); const templates = denseOwnDataArray(rawTemplates, 'compiler templates').map(validateConfigTemplateRegistryEntry); const methodsById = new Map(methods.map((method) => [method.id, method])); const templatesById = new Map(templates.map((template) => [template.methodId, template])); const identities = new Set<string>(); for (const method of methods) for (const identity of [method.id, ...method.aliases]) { const normalized = identity.toLowerCase(); if (identities.has(normalized)) throw new Error('duplicate canonical method identity'); identities.add(normalized) } if (!methods.length || methodsById.size !== methods.length || templatesById.size !== templates.length || methods.length !== templates.length || methods.some((method) => !templatesById.has(method.id))) throw new Error('compiler registries must be complete'); for (const method of methods) { const template = templatesById.get(method.id)!; if (template.version !== method.version || !equalArrays(method.outputs, template.outputs)) throw new Error('method/template output or version mismatch') }
  return (input) => { const raw = exact(input, 'compileConfig input', ['outcome', 'profile', 'generatedAt'], ['parameters', 'role', 'adapters']); const outcome = parseOutcome(raw.outcome); const profile = parseProfile(raw.profile); if (outcome.seed !== profile.seed || outcome.receipt.profileFingerprint !== profileFingerprint(profile)) throw new Error('compileConfig outcome/profile receipt mismatch'); if (!rfc3339DateTime(raw.generatedAt)) throw new Error('generatedAt must be an RFC3339 date-time'); const selectedRole = raw.role === undefined ? 'best_fit' : enumValue(raw.role, ['best_fit', 'robust_alternative', 'resource_aware'] as const, 'compileConfig role'); const selectedAdapters = raw.adapters === undefined ? [] : distinct(strings(raw.adapters, 'compileConfig adapters', 0, (adapter) => adapter === 'scFocus' || adapter === 'scRL'), 'compileConfig adapters') as Array<'scFocus' | 'scRL'>; const best = outcome.recommendations.filter((recommendation) => recommendation.roles.includes(selectedRole)); if (best.length !== 1) throw new Error(`exactly one ${selectedRole} recommendation is required`); const method = methodsById.get(best[0].methodId); const template = templatesById.get(best[0].methodId); if (!method || !template) throw new Error('selected recommendation method must use a canonical registry ID'); if (!method.executable) throw new Error('selected method is not executable'); if (filterCompatibleMethods(profile, [method]).compatible.length !== 1) throw new Error('selected method does not satisfy profile hard capabilities'); if (template.version !== method.version || !method.outputs.includes('latent') || !template.outputKeys.latent) throw new Error('method/template mismatch'); const install = shell.exec(method.installCommand); if (!install || install[1] !== `${template.packageName}==${template.packageVersion}`) throw new Error('unsafe install command or package version mismatch'); const supplied = raw.parameters === undefined ? Object.create(null) : ownDataRecord(raw.parameters, 'parameters'); const parameters: Record<string, ParameterValue> = Object.assign(Object.create(null), template.defaultParameters); for (const [key, value] of Object.entries(supplied)) { const definition = template.allowedParameters[key]; if (!pythonIdentifier.test(key) || value === undefined || !definition || typeof value !== definition.type || (typeof value === 'number' && !Number.isFinite(value))) throw new Error(`invalid parameter ${key}`); if (typeof value === 'number' && ((definition.minimum !== undefined && value < definition.minimum) || (definition.maximum !== undefined && value > definition.maximum) || (definition.integer && !Number.isInteger(value)))) throw new Error(`invalid parameter ${key}`); if (definition.enum && !definition.enum.includes(value as ParameterValue)) throw new Error(`invalid parameter ${key}`); parameters[key] = value as ParameterValue }
    const downstream: ExecutableConfig['downstream'] = Object.create(null); for (const adapter of selectedAdapters) { if (adapter === 'scFocus') { const declared = template.downstream?.scFocus; if (!declared) throw new Error(`requested adapter ${adapter} is not verified for ${method.id}`); const branchKey = declared.branchKey ?? template.outputKeys.branch; if (declared.branchKey !== undefined && !template.outputKeys.branch) throw new Error('scFocus requires branch'); downstream.scFocus = { packageName: declared.packageName, packageVersion: declared.packageVersion, installCommand: declared.installCommand, sourceUrl: declared.sourceUrl, importName: declared.importName, functionName: declared.functionName, latentKey: template.outputKeys.latent, ...(branchKey === undefined ? {} : { branchKey }), contributionOutput: declared.contributionOutput } } else { const declared = template.downstream?.scRL; if (!declared) throw new Error(`requested adapter ${adapter} is not verified for ${method.id}`); const pseudotimeKey = declared.pseudotimeKey ?? template.outputKeys.pseudotime; if (!pseudotimeKey || !template.outputKeys.pseudotime) throw new Error('scRL requires pseudotime'); downstream.scRL = { packageName: declared.packageName, packageVersion: declared.packageVersion, installCommand: declared.installCommand, sourceUrl: declared.sourceUrl, importName: declared.importName, functionName: declared.functionName, latentKey: template.outputKeys.latent, pseudotimeKey, decisionOutput: declared.decisionOutput } } }
    const config: ExecutableConfig = { schemaVersion: '1.0', routerVersion: outcome.routerVersion, evidenceVersion: outcome.evidenceVersion, method: { id: method.id, version: method.version, packageName: template.packageName, packageVersion: template.packageVersion, install: method.installCommand }, preprocessing: { modality: profile.modality, normalization: 'library_size_log1p', featureSelection: 'highly_variable_features' }, parameters, outputs: template.outputKeys, downstream, provenance: { recommendationSeed: outcome.seed, methodSource: method.sourceUrl, generatedAt: raw.generatedAt as string, profileFingerprint: profileFingerprint(profile), release: { id: outcome.receipt.release.id, synthetic: outcome.receipt.release.synthetic, configDigest: outcome.receipt.release.configDigest, evidenceDigest: outcome.receipt.release.evidenceDigest }, outcome: { status: 'OK', methodId: method.id } } }; assertExecutableConfigSchema(config); const serialized = serializeConfig(config); const stem = `${method.id}-${outcome.routerVersion}-seed-${outcome.seed}`; const lines = [`from ${template.importName} import ${template.constructor}`]; if (config.downstream.scFocus) lines.push(`from ${config.downstream.scFocus.importName} import ${config.downstream.scFocus.functionName}`); if (config.downstream.scRL) lines.push(`from ${config.downstream.scRL.importName} import ${config.downstream.scRL.functionName}`); lines.push('', `model = ${template.constructor}(`); for (const key of Object.keys(parameters).sort()) lines.push(`    ${key}=${python(parameters[key])},`); lines.push(')', `result = model.${template.wrapper.fitMethod}(${template.wrapper.input})`); const targets = { latent: 'obsm', graph: 'obsp', pseudotime: 'obs', branch: 'obs', metadata: 'uns' } as const; for (const output of template.outputs) lines.push(`adata.${targets[output]}[${python(config.outputs[output])}] = result.${template.wrapper.resultAttributes[output]}`); if (config.downstream.scFocus) lines.push(`${config.downstream.scFocus.functionName}(adata, latent_key=${python(config.downstream.scFocus.latentKey)}, branch_key=${python(config.downstream.scFocus.branchKey)}, contribution_output=${python(config.downstream.scFocus.contributionOutput)})`); if (config.downstream.scRL) lines.push(`${config.downstream.scRL.functionName}(adata, latent_key=${python(config.downstream.scRL.latentKey)}, pseudotime_key=${python(config.downstream.scRL.pseudotimeKey)}, decision_output=${python(config.downstream.scRL.decisionOutput)})`); const installCommands = [method.installCommand, ...selectedAdapters.map((adapter) => template.downstream![adapter]!.installCommand)]; return freeze({ config: validateExecutableConfig(config), ...serialized, installCommand: method.installCommand, installCommands, pythonSnippet: `${lines.join('\n')}\n`, filenames: { json: `${stem}.json`, yaml: `${stem}.yaml`, python: `${stem}.py` } }) }
}
